package hans.Settings;

public enum SettingsState {
    CLOSED,
    HOME_OPEN,
    PLAYBACK_SPEED_OPEN,
    CUSTOM_SPEED_OPEN,
    PLAYBACK_OPTIONS_OPEN,
    CAPTIONS_PANE_OPEN,
    CAPTIONS_OPTIONS_OPEN,
    FONT_FAMILY_OPEN,
    FONT_COLOR_OPEN,
    FONT_SIZE_OPEN,
    TEXT_ALIGNMENT_OPEN,
    BACKGROUND_COLOR_OPEN,
    BACKGROUND_OPACITY_OPEN,
    LINE_SPACING_OPEN,
    OPACITY_OPEN
}
