package hans.Menu;

public enum MenuState {
    CLOSED,
    QUEUE_OPEN,
    METADATA_EDIT_OPEN,
    TECHNICAL_DETAILS_OPEN,
    CHAPTERS_OPEN,
    SETTINGS_OPEN,
    RECENT_MEDIA_OPEN,
    MUSIC_LIBRARY_OPEN,
    PLAYLISTS_OPEN
}