package tengy.Menu;

public enum MenuState {
    CLOSED,
    QUEUE_OPEN,
    MEDIA_INFORMATION_OPEN,
    CHAPTERS_OPEN,
    SETTINGS_OPEN,
    RECENT_MEDIA_OPEN,
    MUSIC_LIBRARY_OPEN,
    PLAYLISTS_OPEN
}