module hans {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires javafx.media;
    requires javafx.base;
    requires MaterialFX;
    requires com.jfoenix;
    requires org.apache.logging.log4j;
    requires FX.BorderlessScene;
    requires uk.co.caprica.vlcj;
    requires uk.co.caprica.vlcj.javafx;
    requires com.sun.jna.platform;
    requires java.logging;
    requires jaffree;
    requires org.bytedeco.javacv;
    requires org.bytedeco.javacpp;
    requires org.bytedeco.ffmpeg;
    requires com.sandec.mdfx;
    requires java.prefs;
    requires com.google.gson;
    requires java.net.http;

    opens fxplayer to javafx.graphics, javafx.fxml;
    exports fxplayer;
    exports fxplayer.mediaItems;
    opens fxplayer.mediaItems to javafx.fxml, javafx.graphics;
    exports fxplayer.playbackSettings;
    opens fxplayer.playbackSettings to javafx.fxml, javafx.graphics;
    exports fxplayer.menu;
    opens fxplayer.menu to javafx.fxml, javafx.graphics;
    exports fxplayer.subtitles;
    opens fxplayer.subtitles to javafx.fxml, javafx.graphics;
    exports fxplayer.windowstoolbar;
    exports fxplayer.chapters;
    opens fxplayer.chapters to javafx.fxml, javafx.graphics;
    exports fxplayer.openSubtitles;
    exports fxplayer.openSubtitles.models;
    exports fxplayer.openSubtitles.tools;
    exports fxplayer.openSubtitles.models.subtitles;
    exports fxplayer.openSubtitles.models.authentication;
    exports fxplayer.openSubtitles.models.features;
    exports fxplayer.openSubtitles.models.discover;
    exports fxplayer.openSubtitles.models.utilities;
    exports fxplayer.openSubtitles.models.download;
    exports fxplayer.openSubtitles.models.infos;
    exports fxplayer.menu.Queue;
    opens fxplayer.menu.Queue to javafx.fxml, javafx.graphics;
    exports fxplayer.menu.Settings;
    opens fxplayer.menu.Settings to javafx.fxml, javafx.graphics;
    exports fxplayer.srtParser.srt;
    exports fxplayer.windows;
    opens fxplayer.windows to javafx.fxml, javafx.graphics;
    exports fxplayer.windows.chapterEdit;
    opens fxplayer.windows.chapterEdit to javafx.fxml, javafx.graphics;
    exports fxplayer.menu.Settings.Libraries;
    opens fxplayer.menu.Settings.Libraries to javafx.fxml, javafx.graphics;
    exports fxplayer.windows.equalizer;
    opens fxplayer.windows.equalizer to javafx.fxml, javafx.graphics;
    exports fxplayer.windows.openSubtitles;
    opens fxplayer.windows.openSubtitles to javafx.fxml, javafx.graphics;
    exports fxplayer.windows.mediaInformation;
    opens fxplayer.windows.mediaInformation to javafx.fxml, javafx.graphics;
    exports fxplayer.skins;
    opens fxplayer.skins to javafx.fxml, javafx.graphics;
    exports fxplayer.windows.mediaInformation.components;
    opens fxplayer.windows.mediaInformation.components to javafx.fxml, javafx.graphics;
    exports fxplayer.windows.mediaInformation.items;
    opens fxplayer.windows.mediaInformation.items to javafx.fxml, javafx.graphics;
    exports fxplayer.focuscontrol;
    opens fxplayer.focuscontrol to javafx.fxml, javafx.graphics;
}