module hans {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires javafx.media;
    requires javafx.base;
    requires MaterialFX;
    requires com.jfoenix;
    requires org.apache.logging.log4j;
    requires FX.BorderlessScene;
    requires uk.co.caprica.vlcj;
    requires uk.co.caprica.vlcj.javafx;
    requires com.sun.jna.platform;
    requires java.logging;
    requires jaffree;
    requires org.bytedeco.javacv;
    requires org.bytedeco.javacpp;
    requires org.bytedeco.ffmpeg;
    requires com.sandec.mdfx;
    requires java.prefs;
    requires com.google.gson;
    requires java.net.http;

    opens tengy to javafx.graphics, javafx.fxml;
    exports tengy;
    exports tengy.mediaItems;
    opens tengy.mediaItems to javafx.fxml, javafx.graphics;
    exports tengy.playbackSettings;
    opens tengy.playbackSettings to javafx.fxml, javafx.graphics;
    exports tengy.menu;
    opens tengy.menu to javafx.fxml, javafx.graphics;
    exports tengy.subtitles;
    opens tengy.subtitles to javafx.fxml, javafx.graphics;
    exports tengy.windowstoolbar;
    exports tengy.chapters;
    opens tengy.chapters to javafx.fxml, javafx.graphics;
    exports tengy.openSubtitles;
    exports tengy.openSubtitles.models;
    exports tengy.openSubtitles.tools;
    exports tengy.openSubtitles.models.subtitles;
    exports tengy.openSubtitles.models.authentication;
    exports tengy.openSubtitles.models.features;
    exports tengy.openSubtitles.models.discover;
    exports tengy.openSubtitles.models.utilities;
    exports tengy.openSubtitles.models.download;
    exports tengy.openSubtitles.models.infos;
    exports tengy.menu.Queue;
    opens tengy.menu.Queue to javafx.fxml, javafx.graphics;
    exports tengy.menu.Settings;
    opens tengy.menu.Settings to javafx.fxml, javafx.graphics;
    exports tengy.srtParser.srt;
    exports tengy.windows;
    opens tengy.windows to javafx.fxml, javafx.graphics;
    exports tengy.windows.chapterEdit;
    opens tengy.windows.chapterEdit to javafx.fxml, javafx.graphics;
    exports tengy.menu.Settings.Libraries;
    opens tengy.menu.Settings.Libraries to javafx.fxml, javafx.graphics;
    exports tengy.windows.equalizer;
    opens tengy.windows.equalizer to javafx.fxml, javafx.graphics;
    exports tengy.windows.openSubtitles;
    opens tengy.windows.openSubtitles to javafx.fxml, javafx.graphics;
    exports tengy.windows.mediaInformation;
    opens tengy.windows.mediaInformation to javafx.fxml, javafx.graphics;
    exports tengy.skins;
    opens tengy.skins to javafx.fxml, javafx.graphics;
    exports tengy.windows.mediaInformation.components;
    opens tengy.windows.mediaInformation.components to javafx.fxml, javafx.graphics;
    exports tengy.windows.mediaInformation.items;
    opens tengy.windows.mediaInformation.items to javafx.fxml, javafx.graphics;
}