package tengy.subtitles;

public enum SubtitlesState {
    CAPTIONS_OPTIONS_OPEN,
    CLOSED,
    HOME_OPEN,
    FONT_FAMILY_OPEN,
    FONT_COLOR_OPEN,
    FONT_SIZE_OPEN,
    TEXT_ALIGNMENT_OPEN,
    BACKGROUND_COLOR_OPEN,
    BACKGROUND_OPACITY_OPEN,
    LINE_SPACING_OPEN,
    OPACITY_OPEN,
    TIMING_OPEN,
}
