package tengy.Windows.OpenSubtitles;

import java.util.HashMap;

public class Languages extends HashMap<String, String> {
    Languages(){
        this.put("Abkhazian", "abk");
        this.put("Afrikaans", "afr");
        this.put("Albanian", "alb");
        this.put("Arabic", "ara");
        this.put("Aragonese", "arg");
        this.put("Armenian", "arm");
        this.put("Assamese", "asm");
        this.put("Asturian", "ast");
        this.put("Azerbaijani", "aze");
        this.put("Basque", "baq");
        this.put("Belarusian", "bel");
        this.put("Bengali", "ben");
        this.put("Bosnian", "bos");
        this.put("Breton", "bre");
        this.put("Bulgarian", "bul");
        this.put("Burmese", "bur");
        this.put("Catalan", "cat");
        this.put("Chinese (simplified)", "chi");
        this.put("Chinese (traditional)", "zht");
        this.put("Chinese bilingual", "zhe");
        this.put("Croatian", "hrv");
        this.put("Czech", "cze");
        this.put("Danish", "dan");
        this.put("Dari", "prs");
        this.put("Dutch", "dut");
        this.put("English", "eng");
        this.put("Esperanto", "epo");
        this.put("Estonian", "est");
        this.put("Extremaduran", "ext");
        this.put("Finnish", "fin");
        this.put("French", "fre");
        this.put("Gaelic", "gla");
        this.put("Galician", "glg");
        this.put("Georgian", "geo");
        this.put("German", "ger");
        this.put("Greek", "ell");
        this.put("Hebrew", "heb");
        this.put("Hindi", "hin");
        this.put("Hungarian", "hun");
        this.put("Icelandic", "ice");
        this.put("Igbo", "ibo");
        this.put("Indonesian", "ind");
        this.put("Interlingua", "ina");
        this.put("Irish", "gle");
        this.put("Italian", "ita");
        this.put("Japanese", "jpn");
        this.put("Kannada", "kan");
        this.put("Kazakh", "kaz");
        this.put("Khmer", "khm");
        this.put("Korean", "kor");
        this.put("Kurdish", "kur");
        this.put("Latvian", "lav");
        this.put("Lithuanian", "lit");
        this.put("Luxembourgish", "ltz");
        this.put("Macedonian", "mac");
        this.put("Malay", "may");
        this.put("Malayalam", "mal");
        this.put("Manipuri", "mni");
        this.put("Marathi", "mar");
        this.put("Mongolian", "mon");
        this.put("Montenegrin", "mne");
        this.put("Navajo", "nav");
        this.put("Nepali", "nep");
        this.put("Northern Sami", "sme");
        this.put("Norwegian", "nor");
        this.put("Occitan", "oci");
        this.put("Odia", "ori");
        this.put("Persian", "per");
        this.put("Polish", "pol");
        this.put("Portuguese", "por");
        this.put("Portuguese (BR)", "pob");
        this.put("Portuguese (MZ)", "pom");
        this.put("Pushto", "pus");
        this.put("Romanian", "rum");
        this.put("Russian", "rus");
        this.put("Santali", "sat");
        this.put("Serbian", "scc");
        this.put("Sindhi", "snd");
        this.put("Sinhalese", "sin");
        this.put("Slovak", "slo");
        this.put("Slovenian", "slv");
        this.put("Somali", "som");
        this.put("Spanish", "spa");
        this.put("Spanish (EU)", "spn");
        this.put("Spanish (LA)", "spl");
        this.put("Swahili", "swa");
        this.put("Swedish", "swe");
        this.put("Syriac", "syr");
        this.put("Tagalog", "tgl");
        this.put("Tamil", "tam");
        this.put("Tatar", "tat");
        this.put("Telugu", "tel");
        this.put("Thai", "tha");
        this.put("Toki Pona", "tok");
        this.put("Turkish", "tur");
        this.put("Turkmen", "tuk");
        this.put("Ukrainian", "ukr");
        this.put("Urdu", "urd");
        this.put("Vietnamese", "vie");
        this.put("Welsh", "wel");

    }
}
