package tengy.Windows.OpenSubtitles;

import java.util.HashMap;

public class Languages extends HashMap<String, String> {
    Languages(){
        this.put("Afrikaans", "af");
        this.put("Albanian", "sq");
        this.put("Arabic", "ar");
        this.put("Aragonese", "an");
        this.put("Armenian", "hy");
        this.put("Asturian", "at");
        this.put("Basque", "eu");
        this.put("Belarusian", "be");
        this.put("Bengali", "bn");
        this.put("Bosnian", "bs");
        this.put("Breton", "br");
        this.put("Bulgarian", "bg");
        this.put("Burmese", "my");
        this.put("Catalan", "ca");
        this.put("Chinese (simplified)", "zh-cn");
        this.put("Chinese (traditional)", "zh-tw");
        this.put("Chinese bilingual", "ze");
        this.put("Croatian", "hr");
        this.put("Czech", "cs");
        this.put("Danish", "da");
        this.put("Dutch", "nl");
        this.put("English", "en");
        this.put("Esperanto", "eo");
        this.put("Estonian", "et");
        this.put("Finnish", "fi");
        this.put("French", "fr");
        this.put("Galician", "gl");
        this.put("Georgian", "ka");
        this.put("German", "de");
        this.put("Greek", "el");
        this.put("Hebrew", "he");
        this.put("Hindi", "hi");
        this.put("Hungarian", "hu");
        this.put("Icelandic", "is");
        this.put("Indonesian", "id");
        this.put("Italian", "it");
        this.put("Japanese", "ja");
        this.put("Kazakh", "kk");
        this.put("Khmer", "km");
        this.put("Korean", "ko");
        this.put("Latvian", "lv");
        this.put("Lithuanian", "lt");
        this.put("Luxembourgish", "lb");
        this.put("Macedonian", "mk");
        this.put("Malay", "ms");
        this.put("Malayalam", "ml");
        this.put("Manipuri", "ma");
        this.put("Mongolian", "mn");
        this.put("Montenegrin", "me");
        this.put("Norwegian", "no");
        this.put("Occitan", "oc");
        this.put("Persian", "fa");
        this.put("Polish", "pl");
        this.put("Portuguese", "pt-pt");
        this.put("Portuguese (BR)", "pt-br");
        this.put("Romanian", "ro");
        this.put("Russian", "ru");
        this.put("Serbian", "sr");
        this.put("Sinhalese", "si");
        this.put("Slovak", "sk");
        this.put("Slovenian", "sl");
        this.put("Spanish", "es");
        this.put("Swahili", "sw");
        this.put("Swedish", "sv");
        this.put("Syriac", "sy");
        this.put("Tagalog", "tl");
        this.put("Tamil", "ta");
        this.put("Telugu", "te");
        this.put("Thai", "th");
        this.put("Turkish", "tr");
        this.put("Ukrainian", "uk");
        this.put("Urdu", "ur");
        this.put("Uzbek", "uz");
        this.put("Vietnamese", "vi");
    }
}
