package tengy.windows;

public enum WindowState {
    ADD_YOUTUBE_VIDEO_WINDOW_OPEN,
    CLOSE_CONFIRMATION_WINDOW_OPEN,
    HOTKEY_CHANGE_WINDOW_OPEN,
    LICENSE_WINDOW_OPEN,
    TECHNICAL_DETAILS_WINDOW_OPEN,
    THIRD_PARTY_SOFTWARE_WINDOW_OPEN,
    CHAPTER_EDIT_WINDOW_OPEN,
    MEDIA_INFORMATION_WINDOW_OPEN,
    EQUALIZER_OPEN,
    OPEN_SUBTITLES_OPEN,
    CLOSED
}
